### ISSUE TITLE
Decide on handling path starting with / on *nix

### ISSUE THREAD

**Issue by davidfowl** [aspnet/FileSystem#104]
It's a broken assumption since absolute paths on *nix can start with `/`

**Comment by Eilon** [comment]
@davidfowl we talked in theory about swapping these two checks: https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileProviders.Physical/PhysicalFileProvider.cs#L85-L94

However, I don't think that's right either. The real problem is that on Windows it's easy to tell the difference between a volume-rooted path (`C:\...`) and an absolute path (`\foo\bar`), and on *nix there's no way to differentiate.

Honestly not quite sure how we could fix this even in theory...

**Comment by davidfowl** [comment]
I think we have to drop this behavior completely.

**Comment by cesarbs** [comment]
This somehow. affects https://github.com/aspnet/Universe/issues/304. I had to disable a unit test on *nix which ideally should be run on that platform. However the test gets incorrect results because of the way "/" is being treated.

**Comment by muratg** [comment]
Let's reach a decision here. @davidfowl do you suggest we remove support for relative paths? 

Can we just enforce a `.` in front of relative paths?  (i.e. `./foo/bar/` instead of `/foo/bar`) to differentiate it from absolute paths?

**Comment by davidfowl** [comment]
> @davidfowl do you suggest we remove support for relative paths?

No.

> Can we just enforce a . in front of relative paths? (i.e. `./foo/bar/` instead of `/foo/bar`) to differentiate it from absolute paths?

That's ugly. We can just not support paths that begin with /. Relative paths should just start with nothing. .e.g `foo/bar`.

**Comment by muratg** [comment]
That sounds good to me.

**Comment by muratg** [comment]
@pakrym this also prevents CoreCLR x-plat test runs.  Please look into this after your current item.

**Comment by pranavkm** [comment]
> It's a broken assumption since absolute paths on *nix can start with /

Doesn't the `IFileProvider` root you at the rooted path? It's not meant to be a general purpose representation of the native file system.

**Comment by davidfowl** [comment]
It's about what we allow in the methods. We want to fail for absolute paths.

**Comment by muratg** [comment]
So do we fail on Windows for paths like C:\foo\bar as well?

**Comment by davidfowl** [comment]
Yes I believe we already do

**Comment by pakrym** [comment]
Decided that beheviour is okay, just changing supress message.
https://github.com/aspnet/FileSystem/pull/150

**Comment by muratg** [comment]
Cool, please update the bug title to reflect the decision before checking in.
