### ISSUE TITLE
Having NotFoundFileInfo as public

### ISSUE THREAD

**Issue by csunali** [aspnet/FileSystem#111]
The NotFoundFileInfo class was previously public. It is however set to be internal in recent releases. 

The class is extremely useful when implementing a custom file provider since any custom file provider being developed would naturally have to handle non-existing files.

It is easy to implement a custom NotFoundFileInfo class but that leads to unnecessary/duplicate code.

Thus, I would like to ask if there is a specific reason for NotFoundFileInfo being internal and why the change from the previously available public implementation?

- I can make a pull request and make the necessary change if approved by you guys.

**Comment by muratg** [comment]
@Tratcher Was there a specific reason to make `NotFoundFileInfo`, `NotFoundDirectoryContents` etc  `Internal`?

**Comment by Tratcher** [comment]
Ask @loudej

**Comment by muratg** [comment]
@loudej @lodejard @davidfowl

**Comment by davidfowl** [comment]
Those types are in a .Sources package which is meant to be helper code referenced by your project and internalized. We don't currently publish .Sources packages to nuget.org but it should be possible to reference them via our myget feed

**Comment by csunali** [comment]
If I don't get you wrong, you mean that I should reference the mentioned classes using the .Sources packages directly and use the classes as if they were directly developed within my own projects. 

Can you please confirm?

Thank you.

**Comment by stuartleeks** [comment]
+1 on this question. I am just updating some code from an earlier version to beta5 and was using the NotFoundDirectoryContents and NotFoundFileInfo in my custom file provider. What is the expected way to handle this? I'd rather not duplicate these classes in my own code :-)

**Comment by muratg** [comment]
.Sources packages are not published.  @davidfowl it looks like these would potentially be useful to some folks who are implementing custom file providers. We should consider bringing them back and making them public.

**Comment by Agiclaw** [comment]
+1, Please just change back to public. I was also implementing custom providers...

**Comment by muratg** [comment]
As we're not currently planning to bring these back, current suggestion is to use the .Sources packages directly from MyGet, or from the repo.  Closing this one.
