### ISSUE TITLE
`PhysicalFileProvider.GetFileInfo(".")` returns `NotFoundFileInfo`

### ISSUE THREAD

**Issue by moozzyk** [aspnet/FileSystem#116]
This is because Path.GetFullPath(".") returns the path without the trailing slash and we check if the path is under the root using `.StartsWith()` again the `Root` which does contain trailing slash.

**Comment by muratg** [comment]
@moozzyk Putting this to Backlog as this specific case doesn't seem that common.  Do you know if "/" or "/." would work?

**Comment by moozzyk** [comment]
@muratg I don't remember at the moment - `/` might be special cased. I am not sure if `/` is really helpful - wouldn't it go to the root of the drive? I would think people would probably be more interested to go to the approot?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2558
