### ISSUE TITLE
Support globbing directories in addition to files

### ISSUE THREAD

**Issue by ChengTian** [aspnet/FileSystem#118]
Today we only support globbing files given some patterns. We should allow globbing directories as well.

Sample usage:

```
var matcher = new Matcher();
matcher.AddInclude("submodules/*/src");
var results = matcher.GetResultsInFullPath(solutionRoot);
```

and it turns something like
`[ "solutionRoot/submodules/FileSystem/src", "solutionRoot/submodules/NuGet/src"]`

This is useful in certain scenarios like project resolution.

/cc @troydai

**Comment by ChengTian** [comment]
My beta8 issue https://github.com/aspnet/dnx/issues/2352 depends on this. Assigning to myself.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2557
