### ISSUE TITLE
IFileProvider.Watch feels like a mismatch

### ISSUE THREAD

**Issue by davidfowl** [aspnet/FileSystem#123]
Is file watching really something we want to bolt on to this interface? It feels like we should offer this via another API. Also only PhysicalFileProvder has a reasonable implementation for it. 

/cc @pranavkm @lodejard @kichalla

**Comment by muratg** [comment]
@victorhurdugaci

**Comment by pranavkm** [comment]
Do you have an alternative? If we create a separate `IFileWatcher`, it'll need to know the behavior of the underlying `IFIleProvider` - for instance the embedded one would never fire like you noted.

**Comment by muratg** [comment]
Does this one need a design discussion @davidfowl?

**Comment by pranavkm** [comment]
Offline discussion with @loudej and @davidfowl on this was inconclusive. The one issue that came out of the discussion was that it felt that `IExpirationTrigger` being located in `Microsoft.Framework.Caching.Abstractions` seems like wrong layering. Tracking that as part of https://github.com/aspnet/Caching/issues/108.

Unless folks feel very strong about this, we could close this work item.

**Comment by victorhurdugaci** [comment]
Yeah, close it :) I am heavily using this in dnx-watch

**Comment by davidfowl** [comment]
@victorhurdugaci If you're using this in DNX watch then something is busted. Source files can be outside of the `IFileProvider` root. That's exactly the opposite of what this API is supposed to do.

**Comment by victorhurdugaci** [comment]
I have multiple providers

**Comment by davidfowl** [comment]
Ugh
