### ISSUE TITLE
Enhancement for file providers

### ISSUE THREAD

**Issue by mnguyen284** [aspnet/FileSystem#130]
EmbeddedFileProvider is great for supporting modular programming. We will be able to develop a Blog component that comes with controllers and views and just plug it in a website.

However, because RazorViewEngine only supports 1 file provider, the engine cannot load both views from both plugged in component (embedded) and main website (which are physical files).

Moreover, we don't have a chance to override embedded views neither.

Sugesstion:

1. Support multiple file provider, prioritized by order. Views in later file provider with override ones loaded before. Or

2. Enhance EmbeddedFileProvider to support multiple assemblies and can be overridden by physical files.

**Comment by davidfowl** [comment]
> However, because RazorViewEngine only supports 1 file provider, the engine cannot load both views from both plugged in component (embedded) and main website (which are physical files).

Sure it can, you just need to wrap the 2 file providers you want.

> Enhance EmbeddedFileProvider to support multiple assemblies and can be overridden by physical files.

This sounds like it could be a great pull request. Why don't you file a separate issue for that one (and potentially start work on it :smile: )

**Comment by mnguyen284** [comment]
@davidfowl Thanks for your respond. May I ask what did you mean by wrapping the 2 file providers? Was it creating a custom provider that contains both of them?

I'll try with the option you suggested. Just figuring out the method to pass multiple assemblies and base namespaces to the constructor. Should I use DI and creating an EmbeddedFileProviderOptions class?

**Comment by davidfowl** [comment]
> @davidfowl Thanks for your respond. May I ask what did you mean by wrapping the 2 file providers? Was it creating a custom provider that contains both of them?

Yep. It's basically what you suggested.

`new UberFileProvider(defaultProvider, embeddedProvider)`

**Comment by muratg** [comment]
Closing this one as it looks like #131 tracks the work.
