### ISSUE TITLE
Pass Credentials to PhysicalFileProvider?

### ISSUE THREAD

**Issue by jovnas** [aspnet/FileSystem#141]
(In Startup.cs)

```
app.UseFileServer(new FileServerOptions
{
    RequestPath = new PathString("/webpath"),
    FileProvider = new PhysicalFileProvider(@"\\other.server\share\subfolder"),
    EnableDirectoryBrowsing = false
});
```
This only works if the application is running as a user with access to the share.
I believe that passing specific credentials into the PhysicalFileProvider would be the most straight forward approach. (For example, if you have to map multiple shares on different servers with different user credentials.)

(If I've missed something, please point me in the right direction and scratch this issue... :-) )

**Comment by davidfowl** [comment]
What's the usual API for doing this in .NET? What form do credentials take? Is it OS specific?

**Comment by jovnas** [comment]
I'm barking up the wrong tree again, I guess...
Didn't think it through before creating this issue. My original problem is probably not related to FileSystem, but to the IisPlatformHandler. (Probably it's not even a problem there, but in my lack of knowledge about how Asp.Net5 works with IIS... See http://stackoverflow.com/questions/33253608/asp-net-5-beta8-app-with-virtual-directories-applications )
