### ISSUE TITLE
Modify MatcherContext so that it returns an IEnumerable

### ISSUE THREAD

**Issue by reliak** [aspnet/FileSystem#143]
In https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileSystemGlobbing/Internal/MatcherContext.cs#L44 the `Execute` method returns a `PatternMatchingResult` object.

To better support parallel operations, it would be great to return an `IEnumerable<FilePatternMatch>` with an `yield` inside the `Execute` method. This way I can start working when the first file was found and I do not need to wait till the end of the `Execute` method.

**Comment by muratg** [comment]
`PatternMatchingResult` has `Files` property which is an `IEnumerable<FilePatternMatch>`.

Though if you look at https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileSystemGlobbing/Internal/MatcherContext.cs#L35, this is already not lazy. 

Do you have any measurements to suggest a design change?

**Comment by reliak** [comment]
I haven't done any performance measurements, so I can't tell you whether it's worth to change the design.
But yielding a result when it's found should perform better in terms of parallelization, instead of collecting all results and then returning all at once.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2556
