### ISSUE TITLE
Matcher returns wrong stems

### ISSUE THREAD

**Issue by reliak** [aspnet/FileSystem#144]
This addresses issue https://github.com/aspnet/Announcements/issues/58

I have the following folder structure:
- root
  - subfolder
    - sub1
    - sub2
    - sub3

I wanna find all files via:
```
var m = new Matcher();
m.AddInclude(@"**/*.*");
var res = m.Execute(new DirectoryInfoWrapper(new DirectoryInfo(root)));
```
As shown below, the Stems for files in `sub2` and `sub3` are wrong.
![globissue](https://cloud.githubusercontent.com/assets/4062774/11366023/d827b936-92aa-11e5-8dec-f0d500d18d79.png)

When I use a glob pattern starting with `subfolder` (see below) instead of the wildcards, all stems are correct:
```
var m = new Matcher();
m.AddInclude(@"subfolder/**/*.*");
var res = m.Execute(new DirectoryInfoWrapper(new DirectoryInfo(root)));
```
**Update**: Apparently the problem is not the glob pattern at the beginning. I inserted a folder under `subfolder`. When I now use the above pattern (`"subfolder/**/*.*"`) I also get wrong stems.

/cc @anurse

**Comment by anurse** [comment]
I think I've seen this before. @muratg we should work on this for RC2.

**Comment by muratg** [comment]
Agreed!

**Comment by BrennanConroy** [comment]
a6ffb85a267cdc8f5985363bfc909904650003d5
