### ISSUE TITLE
Suggest to make NotFoundFileInfo and NoopChangeToken public

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/FileSystem#145]

**Comment by Eilon** [comment]
Can you clarify the reason for wanting them public? Are you writing a custom file system provider? Or something else?

**Comment by PrimeObjects** [comment]
I'm writing a ViewFileProvider, I hope this FileProvider can serve MVC by using view files saved in the database.

I need to return NoopChangeToken and NotFoundFileInfo like what RazorEmbeddedFileProvider did.
I want to use the one defined in .NET in my class directly.
e.g.
public IChangeToken Watch(string pattern)
        {
            return NoopChangeToken.Singleton;
        }

**Comment by Eilon** [comment]
Ah, got it. So just for code re-use, which sounds fine. Just wanted to make sure it wasn't for checking equality, which would be wrong (e.g. checking `if (foo.GetType() == typeof(NoopChangeToken))` and making some decision based on that.

**Comment by PrimeObjects** [comment]
thank you for reminding. I cloned the two classes into my namespace for now. if you decide to make the two classes public I should be able use them directly. 

Thanks again.
Gary

**Comment by mgrosperrin** [comment]
Hi,
maybe we could provide a factory to create _empty_ implementation of these types (`IFileInfo`, `IDirectoryContents` and `IChangeToken`). This would protect against comparing the type (except if people do scary things like `foo.GetType() == factory.GetXXX().GetType()`) and allow reuse of the types.
I can provide you a PR to prototype it if needed (I just need a name for the project hosting the factory :smile:).

**Comment by pranavkm** [comment]
@PrimeObjects all of these packages are in the `Microsoft.AspNet.FileProviders.Sources` package. You should be able to reference them and use that.

**Comment by mgrosperrin** [comment]
@pranavkm I have tried to do this for my composite file provider, but the `Microsoft.AspNet.FileProviders.Sources` package has not been published in the RC1 wave. Will it be published as part of RC2 (it is in the nightly) ?

**Comment by pranavkm** [comment]
We don't publish any of the Sources packages to NuGet.org. You'd have to pick it up from `aspnetmaster`.

**Comment by Driedas** [comment]
I second this suggestion, my use case is a custom IFileProvider that internally wraps the PhysicalFileProvider to provide a virtual file system, returning files based on other criteria than just the file path. If all criteria fails to find the requested file, I would like to return NotFoundFileInfo directly. Returning null just yields a NullReferenceException in Microsoft.AspNet.StaticFiles.StaticFileContext.LookupFileInfo()

**Comment by MiloSmith** [comment]
I agree with this, I am using SaasKit and have a tenant context. My file provider takes that context into account and servers up files based on the tenant. I had to copy several classes into my code from the source, and that is a pretty ugly solution. Because of this, I get the impression that you guys don't want us making new file providers. Is that the correct? Am I missing something here?

**Comment by pranavkm** [comment]
@Eilon - thoughts on publishing the NoOp* types from Sources into Abstractions?

**Comment by Eilon** [comment]
In 1.0.1. No time in this milestone.

**Comment by Driedas** [comment]
I understand you guys are all swamped at the moment to get to RTM, so would you accept a pull request with this change?

**Comment by Eilon** [comment]
@Driedas we would certainly consider it, though of course it's difficult to guarantee anything 😄

**Comment by Driedas** [comment]
@Eilon implemented suggestion by @pranavkm in PR https://github.com/aspnet/FileSystem/pull/195

**Comment by Eilon** [comment]
Assigning to @pranavkm because he's taking care of the PR.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/FileSystem/commit/f282bcee933debdbcb9765c51eeb4ef2ca190efc
