### ISSUE TITLE
Support for globbing in FileSystemWatcher?

### ISSUE THREAD

**Issue by reliak** [aspnet/FileSystem#149]
Is it planned to add globbing support to `FileSystemWatcher`?
That would be really helpful.

As an alternative, is it in the current `Microsoft.Extensions.FileSystemGlobbing` project possible, to validate whether a given filename matches a glob pattern?

**Comment by muratg** [comment]
FileSystemWatcher is a CoreCLR class.  Please feel free to file an issue on https://github.com/dotnet/corefx for this request.

Your second question, we don't have this planned for V1.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2555
