### ISSUE TITLE
NoOpChangeToken.RegisterChangeCallback should not throw

### ISSUE THREAD

**Issue by pranavkm** [aspnet/FileSystem#154]
Per @loudej, the intent of `ActiveChangeCallbacks` is a hint for consumers to prefer the property over callback. However `RegisterChangeCallback` should have a proper implementation and should not throw. This also affects `CompositeFileProvider` where we ignore change tokens with `ActiveChangeCallback == false`.

**Comment by muratg** [comment]
Assigning to @pranavkm to merge the PR.  Thanks @mgrosperrin for the contribution!
