### ISSUE TITLE
Un-nest private implentations of IFileInfo and IDirectoryContents

### ISSUE THREAD

**Issue by mgrosperrin** [aspnet/FileSystem#156]
As said in https://github.com/aspnet/FileSystem/pull/142#discussion_r45883155, the private implementations of `IFileInfo` and `IDirectoryContents` should be un-nest and made public.
I can submit a PR to do it.

**Comment by pranavkm** [comment]
:+1: We got some of the `PhysicalFileProvider` ones made public in a recent PR. Would be nice to make the remainder public too.

**Comment by muratg** [comment]
@mgrosperrin Feel free to submit a PR!  Thanks

**Comment by pranavkm** [comment]
For this change, would it make sense to move the non-primary API to a nested namespace?
For instance:

* `Microsoft.AspNet.FileProviders.PhysicalFileProvider`
* `Microsoft.AspNet.FileProviders.Physical.PhysicalDirectoryInfo` (this would match the project name).

This way we don't end up polluting the top level namespace when making the less common types public.

**Comment by muratg** [comment]
Yeah, I think it makes sense. Of course it's hard to find good names for the namespace.

**Comment by pranavkm** [comment]
I'll send a PR - we can discuss it as part of it.
