### ISSUE TITLE
Test failure on OSX/Mono

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/FileSystem#159]
```
Microsoft.AspNet.FileProviders.PhysicalFileProviderTests.TokenIsSameForSamePathCaseInsensitive [FAIL]
      Assert.Equal() Failure
      Expected: FileChangeToken { ActiveChangeCallbacks = True, HasChanged = True, Pattern = "4e3295a4-ec03-434c-b9e0-7ca38f358f6a" }
      Actual:   FileChangeToken { ActiveChangeCallbacks = True, HasChanged = False, Pattern = "4e3295a4-ec03-434c-b9e0-7ca38f358f6a" }
```

https://travis-ci.org/aspnet/FileSystem/jobs/102491783#L1332

**Comment by muratg** [comment]
Is the test disabled now for Mono?

**Comment by muratg** [comment]
@BrennanConroy could you have a look if this is still an issue?

**Comment by BrennanConroy** [comment]
I am hitting this on Mono OSX as well, but also on Linux CoreCLR

**Comment by BrennanConroy** [comment]
Also this test is failing: `TokensWithForwardAndBackwardSlashesAreSame`
I think https://github.com/aspnet/FileSystem/blob/befcc5b974d060b011efa1f7655e1ca538da601c/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFilesWatcher.cs#L149-L151 is wrong because it converts `\` on unix to `/`.
Is this supposed to be case insensitive matching even on unix?

**Comment by muratg** [comment]
Don't remember the final decision on that one.  

cc @troydai @davidfowl

**Comment by troydai** [comment]
We haven't make decision in terms of `PhysicalFilesWatcher`. We did decide the globbing will be case insensitive across platform.

**Comment by BrennanConroy** [comment]
@davidfowl 
Could we make a decision for this?

**Comment by BrennanConroy** [comment]
@Eilon 
Should the PhysicalFilesWatcher respect Unix '/' '\' differences and case sensitivity?

**Comment by Eilon** [comment]
You mean we'd effectively be normalizing `/` and `\`?

**Comment by muratg** [comment]
I think yes for normalizing "/" and "\".  Not sure where we landed on case sensitivity...

**Comment by davidfowl** [comment]
@BrennanConroy lets talk about this tomorrow

**Comment by BrennanConroy** [comment]
/ at beginning of path is "correct"
\\ to / in Watcher will be backlogged
Case sensitivity in Watcher could be made a flag in future
