### ISSUE TITLE
Need to account for case sensitivity in paths in *nix systems

### ISSUE THREAD

**Issue by pranavkm** [aspnet/FileSystem#16]
Based on discussion here - https://github.com/aspnet/FileSystem/pull/15/files#r16609383

**Comment by davidfowl** [comment]
@pranavkm was this fixed?

**Comment by pranavkm** [comment]
Looking at https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileProviders.Physical/PhysicalFileProvider.cs#L56-L59, presumably not.

**Comment by pranavkm** [comment]
Looking at the code, this might be one of the problematic scenarios:

`var result = new PhysicalFileSystem("/foo/bar").GetDirectoryContents("/Foo/bar");`

Expected: `NotFoundDirectoryContents`
Actual: Returns results under `/Foo/bar`

**Comment by muratg** [comment]
Are we doing this? Priority for RC1?

**Comment by Yves57** [comment]
While working on a ZIP File Provider (see #213), I encountered the problem.

Just by curiosity, for the code `new PhysicalFileSystem("/foo/bar").GetFileInfo("/FOO/BAR")` that returns different result on Unix and Windows:
- It is the user responsability to find a solution.
- It is the provider responsability, so the future code should be `new PhysicalFileSystem("/foo/bar", ignoreCase: true).GetFileInfo("/FOO/BAR")`.
- It is the caller responsability, so the future code should be `new PhysicalFileSystem("/foo/bar").GetFileInfo("/FOO/BAR", ignoreCase: true)`. In my opinion the most versatile and clear, but with interface breaking change.

**Comment by davidfowl** [comment]
We're not going to make the file system provider case insensitive, that requires caching and all the problems that come along with it. It's unfortunate that file systems are case sensitive but this API isn't trying to fix that.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2570
