### ISSUE TITLE
Move all the packages and namespaces from AspNet to Extensions in this repo

### ISSUE THREAD

**Issue by muratg** [aspnet/FileSystem#160]
These are not ASP.NET specific libraries, and can be used elsewhere. 

Also, there's a layering issue with https://github.com/aspnet/Configuration/blob/dev/src/Microsoft.Extensions.Configuration.FileProviderExtensions/project.json#L13.

**Comment by muratg** [comment]
@BrennanConroy Per @NTaylorMullen, we can do this now before the renames go in.  This will also require an Announcements post.

cc @Eilon @lodejard @davidfowl

**Comment by lodejard** [comment]
Very nice

**Comment by BrennanConroy** [comment]
befcc5b974d060b011efa1f7655e1ca538da601c
