### ISSUE TITLE
[Discussion]: FileProviders moved to Extensions namespace

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/FileSystem#162]

**Comment by Daniel15** [comment]
What does "Extensions" mean in this context?

**Comment by pranavkm** [comment]
It's the term we've been using for all packages that aren't primarily related to the server stack. See https://github.com/aspnet/Announcements/issues/77

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
