### ISSUE TITLE
CompositeFileProvider has a issue with Watch

### ISSUE THREAD

**Issue by SebastianStehle** [aspnet/FileSystem#164]
Hi, I am using the CompositeFileProvider with multiple phyiscal paths.

The problem is  the following: The PhysicalFileProvider returns a change token, also when the file does not exits. Therefore the first provider returns a token and the if the file is provided from the another provider it will not be refreshed. I solved it in the following way, but I dont know if it is correct:

        public IChangeToken Watch(string filter)
        {
            foreach (IFileProvider fileProvider in this.fileProviders)
            {
                var fileOrFolder = fileProvider.GetFileInfo(filter);

                if (fileOrFolder.Exists)
                {
                    IChangeToken changeToken = fileProvider.Watch(filter);

                    if (changeToken != null)
                        return changeToken;
                }
            }

            foreach (IFileProvider fileProvider in this.fileProviders)
            {
                IChangeToken changeToken = fileProvider.Watch(filter);

                if (changeToken != null)
                    return changeToken;
            }

            return NonexistentChangeToken.Singleton;
        }

The more correct solution would be to make a composite change token:

    internal class CompositeChangeTokenRegistrations : IDisposable
    {
        private readonly IDisposable[] registrations;

        public CompositeChangeTokenRegistrations(IDisposable[] registrations)
        {
            this.registrations = registrations;
        }

        public void Dispose()
        {
            foreach (var registration in registrations)
            {
                registration.Dispose();
            }
        }
    }

    internal class CompositeChangeToken : IChangeToken
    {
        private readonly IChangeToken[] tokens;

        public CompositeChangeToken(IChangeToken[] tokens)
        {
            this.tokens = tokens;
        }

        public IDisposable RegisterChangeCallback(Action<object> callback, object state)
        {
            return new CompositeChangeTokenRegistrations(
                tokens.Select(token =>
                {
                    try
                    {
                        return token.RegisterChangeCallback(callback, state);
                    }
                    catch (NotSupportedException)
                    {
                        return null;
                    }
                }).Where(x => x != null).ToArray());
        }

        public bool HasChanged
        {
            get { return tokens.Any(x => x.HasChanged); }
        }

        public bool ActiveChangeCallbacks
        {
            get { return tokens.Any(x => x.ActiveChangeCallbacks); }
        }
    }

    public IChangeToken Watch(string filter)
        {
            IChangeToken[] tokens = fileProviders.Select(p => p.Watch(filter)).Where(x => x != null).ToArray();

            if (tokens.Length > 0)
            {
                return new CompositeChangeToken(tokens);
            }

            return NonexistentChangeToken.Singleton;
        }

**Comment by pranavkm** [comment]
Doesn't the `CompositeFileChangeToken` raise a call back when any of the file provider has a change event? The ordering shouldn't matter. Might be useful if you could set up a minimal repro scenario where it doesn't work.

**Comment by SebastianStehle** [comment]
Yes, this is the idea. Let me explain the issue again. Lets say you have two folders for your views:

1. App/Views
2. Plugin/Views

The providers for these folders are registered in this order. The view your are looking for only exists in the second folder. In the current implementation you would ask each provide for a change token and the first wins and returns a token (because you might add the file later). So you dont receive the the updates in the plugin folder. Therefore you need both tokens. 

I think it would be correct to watch all folders, especially for views, because you support different locations (Shared, Controller ... ). This is very useful and can be extended for theming or multi-tenancy scenarios also. But in these use cases it might happen that you add and remove files during runtime. Therefore you need to watch for changes in all folders.

**Comment by pranavkm** [comment]
> in the current implementation you would ask each provide for a change token and the first wins and returns a token

That's not how it works: https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Composite/CompositeFileProvider.cs#L78. It should return a change token that represents the aggregate. If you're seeing otherwise, it'd be a nice to get a repro since it sounds like a bug.

**Comment by SebastianStehle** [comment]
I am so confused, I dont know which Code i had a look to, probably an old version. Everything looks fine
