### ISSUE TITLE
PhysicalFileWatcher produces regexes for non-wildcard patterns

### ISSUE THREAD

**Issue by pranavkm** [aspnet/FileSystem#182]
Noticed this when I was debugging test. When Mvc.Razor uses `Watch` we only ever use absolute paths to Razor and never uses wildcard. Might be worth investigating if we can avoid generating extra `Regex` instances

**Comment by muratg** [comment]
:+1:

**Comment by pranavkm** [comment]
This was fixed as part of https://github.com/aspnet/FileSystem/commit/c22515597524dfad7f65717cb7e759b9dd7236b6. We now expand the pattern when `Watch` is called.
