### ISSUE TITLE
Rename events on PhysicalFileWatcher can throw - Crashing VS.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/FileSystem#187]
In some of Visual Studios test cases when they open a file => new web app 50+ times they eventually encounter crashes [here](https://github.com/aspnet/FileSystem/blob/01c1e95ae57456fb143a56d086a510082848d02c/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFilesWatcher.cs#L133). Essentially `Directory.EnumerateFileSystemEntries` explodes due to a node_modules file being renamed then locked.

This is a problem for Visual Studio because it ends up crashing it; however, it is infrequent. This can be mitigated by changing Mvc/Razor to only monitor the Views folder, it currently gets file watcher change events for all of the node_modules folder additions/renames during restore. This can also be fixed across the board by catching around this logic.

Not sure of the severity of this issue.

/cc @Eilon @ToddGrun @pranavkm

**Comment by Eilon** [comment]
@NTaylorMullen this shouldn't crash VS no matter what. Did you open a VS bug?

**Comment by ToddGrun** [comment]
VS doesn't own any of the code on this stack. The exception never gets caught and ends up crashing VS.

**Comment by Eilon** [comment]
@ToddGrun hmm then how does it crash VS?

**Comment by ToddGrun** [comment]
@Eilon -- An unhandled exception on a background thread will kill VS.

**Comment by Eilon** [comment]
Ah, background thread, got it!

**Comment by Eilon** [comment]
@muratg @DamianEdwards should we consider a hot-fix here for RC2 to at least try-catch? And do a better fix for RTM?

**Comment by muratg** [comment]
@Eilon yes, I think a simple fix in RC2 is worthy, considering how bad the experience is.

**Comment by Eilon** [comment]
@muratg can you send email for approval?

**Comment by NTaylorMullen** [comment]
98ea34e732734413da699959dd0342033de8c149

**Comment by DamianEdwards** [comment]
@NTaylorMullen that commit is in to `dev`, is this going in to `release` as well?

**Comment by NTaylorMullen** [comment]
Oops pasted the dev commit instead of the release commit (it went into release first).
