### ISSUE TITLE
Default EmbeddedFileProvider baseNamespace parameter to assembly name

### ISSUE THREAD

**Issue by pakrym** [aspnet/FileSystem#190]
Lets take assembly named `MyCompany.MyApplication` with embedded folder `wwwroot` that has `text.txt` file in it.

When using `EmbeddedFileProvider.ctor(Assembly assembly)` it will set `baseNamespace` to empty by default, so URL will look like: `http://localhost/MyCompany/MyApplication/wwwroot/text.txt`.

If we change it's behavior to set `baseNamespace` to assembly name it will look like `http://localhost/wwwroot/text.txt`, which in my opinion is more desirable.

In `dotnet cli` namespace for embedded files defaults to project name, and assembly name default's to it too, so this change would cover most of cli use cases.

**Comment by muratg** [comment]
Do we currently support multiple assemblies for the file provider?  If we go with this proposal, and and if there's a clash in the folder name, what happens?

**Comment by muratg** [comment]
Ping

**Comment by muratg** [comment]
@pakrym Let's make this change in RTM. Once done make sure to post an announcement.
