### ISSUE TITLE
IFileProvider - Path Too Long Exception

### ISSUE THREAD

**Issue by dazinator** [aspnet/FileSystem#193]
I'm listing files from an `IFileProvider` by enumerating the files, and filtering based on the file extension. However when accessing `IFileInfo.PhysicalPath` I'm getting a `PathTooLongException`

![image](https://cloud.githubusercontent.com/assets/3176632/15479635/f963432a-2118-11e6-8fb8-5a801bfb7e06.png)

I'm using build `1.0.0-rc2-15922` in an ASP.NET 5 RC1 based application.

Given that the file exists (on Windows), why should it error when accessing it's path?

**Comment by pranavkm** [comment]
The call stack is from `System.IO.Path`. https://github.com/dotnet/corefx/issues would be the right place to file this issue.
