### ISSUE TITLE
File globbing should support pattern checks

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/FileSystem#194]
Today you cannot check if if a path matches a pattern without executing the globbing pattern (aka going to disk). This slows down dotnet watch a lot because on every file change it has to go to the disk, fetch all files and the see if the changed file is in the resulting list.

**Comment by pranavkm** [comment]
Isn't this what FileSystemGlobber does - https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFilesWatcher.cs#L107-L108

**Comment by victorhurdugaci** [comment]
Nope. What I want to do is, given:

1. Base path: `/foo`
2. Pattern: `*.js`

Tell me if `/foo/bar.js` matches that without going to the disk.

**Comment by dazinator** [comment]
> Tell me if /foo/baz/bar.js matches that without going to the disk.

Yes please! Does globbing only work with `PhysicalFileProvider` currently then?

I'd like to take:
1. A pattern `**/*.js`
2. An `IEnumerable<string>` paths - `{"some/path/file1.js", "some/path/file2.js", "someother/file/one.txt"}`  

Tell me what the matches are (without going to disk)

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/FileSystem/commit/767f07ff39ec66e567d73a034f11bda260ab6123
