### ISSUE TITLE
PhysicalFileProvider.GetFileInfo returns NotFoundFileInfo for all absolute paths

### ISSUE THREAD

**Issue by ColinBradleyDriveWorks** [aspnet/FileSystem#202]
This was a pretty confusing error to deal with as it's misleading.

Especially when the absolute path does actually exist.

if something stated that it was an invalid, out of range, or even rooted path, that would be fine.
I don't know what you would complain about though if the path actually fell within or relatable to the root path.

This can be seen with something like:

```
var builder = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
    .SetBasePath(@"D:\MyLovelyAppFolder")
    .AddJsonFile("appsettings.json") // This is ok
    .AddJsonFile(@"C:\Users\Steve\AppData\Roaming\something\usersettings.json", optional: false) // EL DIABLO!

builder.Build(); // Exception with weird file does not exist error (when it does)
```

I appreciate that's more of a https://github.com/aspnet/Configuration example, but you get the idea.

This is all from version RC2.

The "offending" line can be found here:
https://github.com/aspnet/FileSystem/blob/master/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFileProvider.cs#L157

**Comment by davidfowl** [comment]
It's fixed in RTM of configuration https://github.com/aspnet/Configuration/commit/009a062fc6dd2a49ccef376d1c0e3ca47e252577. This isn't a file system issue, it's a configuration issue.
