### ISSUE TITLE
PhysicalFilesWatcher should defend against PathTooLongException

### ISSUE THREAD

**Issue by Eilon** [aspnet/FileSystem#205]
In the various event handlers in [PhysicalFilesWatcher](https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFilesWatcher.cs), there can be exceptions thrown for paths that are too long. For example, constructing a `FileInfo` with a long path can throw.

Because this code runs in background threads, this can easily take down a process that's using it.

@NTaylorMullen did some related fixes in https://github.com/aspnet/FileSystem/issues/187, but it seems that we need to handle more cases.

See Watson info here: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=186004&_a=edit

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/FileSystem/commit/b58bbe011ab88335d532762740c43381b36244a7
