### ISSUE TITLE
EmbeddedFileProvider - Change _lastModified date to last write time of an assembly

### ISSUE THREAD

**Issue by martinba1** [aspnet/FileSystem#208]
Could you please consider change of _lastModified date to last write time of an assembly? This information would be very useful if you want to use this file provider also for different purposes than Razor View.

File: FileSystem/src/Microsoft.Extensions.FileProviders.Embedded/EmbeddedFileProvider.cs
Current: _lastModified = DateTimeOffset.MaxValue;

My idea is:
if (assembly.Location != null)
    _lastModified = new FileInfo(assembly.Location).LastWriteTime;
else
    _lastModified = DateTimeOffset.MaxValue; 

Thank you

**Comment by muratg** [comment]
Agreed.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/FileSystem/commit/a5366af6614835ea4faff7e35c58604563ba5908
