### ISSUE TITLE
FileSystem should support traversing folders recursively

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/FileSystem#21]
Ala - `System.IO.Directory.EnumerateFiles(path, "*.*", SearchOption.AllDirectories)`

**Comment by muratg** [comment]
@Eilon Do you care about this?  Putting in 1.0.0 backlog for now.

**Comment by Eilon** [comment]
1.0.0 backlog is fine. We're redesigning precompilation anyway so it's not certain that this feature will matter in the new design.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2569
