### ISSUE TITLE
FileSystemGlobbing package should support being hosted by NuGet.exe (target 4.5.0 please)

### ISSUE THREAD

**Issue by rrelyea** [aspnet/FileSystem#212]
We currently munge code from FileSystemGlobbing into nuget assemblies...however, it is exposed as public, which causes conflicts with the real FileSystemGlobbing.

@anurse filed an issue: https://github.com/NuGet/Home/issues/2345 
to ask NuGet to fix.

In order to fix most efficiently, we are asking that you guys downgrade the TFM for FileSystemGlobbing to NetFramework 4.5 from your current 4.5.1.

This is to help us maintain the ability for NuGet.exe to run on machines it currently does...without requiring .NET Framework upgrades for our users.

**Comment by anurse** [comment]
/cc @DamianEdwards @Eilon 

Technically: no problem (as far as I can tell). It's up to people with 'Manager' in their title to figure out if we're OK pulling this down to `net45` ;)

**Comment by muratg** [comment]
I'm fine with this as well (assuming it works :smile:) 

@DamianEdwards @Eilon You guys are fine with this?

**Comment by Eilon** [comment]
Yeah I was gonna approve this. Let's just do it, assuming we don't run into issues.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/FileSystem/commit/ec05b047d305da03c268dae2c5e69abcfa911315
