### ISSUE TITLE
Idea to minimize buffer allocations in PhysicalFileProvider

### ISSUE THREAD

**Issue by davidfowl** [aspnet/FileSystem#215]
Credit goes to @stephentoub 

Pass the minimum buffer size (1) to the FileStream constructor and have callers use pooled buffers for reading.

/cc @pakrym @Tratcher @rynowak

**Comment by pakrym** [comment]
Would read skipping internal buffer in this case?

**Comment by davidfowl** [comment]
That's the idea.

**Comment by pakrym** [comment]
I'll try and profile it tomorrow.

**Comment by pakrym** [comment]
Would be nice to allow passing 0 to `bufferSize` then.

**Comment by stephentoub** [comment]
While it may be nice aesthetically, it shouldn't really impact anything.  The buffer shouldn't be allocated (at least not in corefx), as the buffer is lazily-initialized and will be skipped if the number of bytes to be read is >= bufferSize.

**Comment by muratg** [comment]
@pakrym did it help (if you got the chance to profile)?

**Comment by pakrym** [comment]
Yes, I implemented it. Buffer allocations from `FileStream` are not a problem anymore.
