### ISSUE TITLE
Make DirectoryInfoWrapper implementation details internal

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/FileSystem#229]
Microsoft.Extensions.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper has public API that is really only an implementation detail. We could make some of this to internal instead.

Would be a breaking change, so we can't do this until 2.0.

**Comment by pranavkm** [comment]
We could start by marking it as Obsolete. One alternative after doing so is to clone the type into a separate namespace that we can use without having to pragma suppress the obsolete warning.
