### ISSUE TITLE
Consider adding an InMemoryFileSystem

### ISSUE THREAD

**Issue by pranavkm** [aspnet/FileSystem#231]
@sebastienros was hacking something together for his work where he wanted to shim a file provider backed by strings. It would be nice if there's an InMemoryFileProvider-like type that 

1. Allows adding files as part of the constructor
2. IFileInfo instances that allow being backed up Streams or something like that.

```C#
public class InMemoryFileProvider
{
   public InMemoryFileProvider(IDirectoryInfo rootDirectory);
}

public class DirectoryInfo
{
      public DirectoryInfo(IDirectoryInfo[] subDirectories, IFileInfo[] files)
}

public class FileInfo
{
     public FileInfo(string path, byte[] content);
}
```

Would also help as a nice API for stubbing in tests in particular if we can provide a nice-ish API to construct the file hierarchy.

**Comment by natemcmaster** [comment]
Duplicate of https://github.com/aspnet/FileSystem/issues/221?

**Comment by pranavkm** [comment]
Totally.
