### ISSUE TITLE
Modify PollingWildCardChangeToken to include the timestamp of the files along with the names as part of hash check

### ISSUE THREAD

**Issue by pranavkm** [aspnet/FileSystem#238]
Consider the following timeline

```
t0 ->  Create a copy of  File.txt to a backup directory . 
t1 -> Modify File.txt with contents different from the original file.
t2 -> Move the file from the backup directory to the original location.
```

The `PollingWildCardChangeToken` only carries the timestamp of the most recently changed last write time window. Consequently this wouldn't work when a file is modified but it's timestamp hasn't moved forward. We could avoid this by additionally storing the timestamp along with the name of the file.

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by Eilon** [comment]
Not a task. This is a genuine bug. Tasks are for code cleanup!
