### ISSUE TITLE
[BREAKING CHANGE] public class Microsoft.Extensions.FileProviders.FileSystemInfoHelper was made static

### ISSUE THREAD

**Issue by javiercn** [aspnet/FileSystem#243]
V1:
`public class FileSystemInfoHelper`
V2:
`public static class FileSystemInfoHelper`

[ACTION for 1.1]: Undo the breaking change.
[ACTION for 2.0]: Make the class internal.

**Comment by javiercn** [comment]
@Eilon @muratg

**Comment by natemcmaster** [comment]
Mea culpa. 0e2180335d6d9156840fbf8a4dca0c9c1ee77509

**Comment by Eilon** [comment]
No biggie, let's just make it un-static and we'll fix it in 2.0.
