### ISSUE TITLE
Watch() - Exclude pattern

### ISSUE THREAD

**Issue by dazinator** [aspnet/FileSystem#253]
When watching() it's often quite useful to watch based on an include list and an exclude list.

For example watch all *.js files, except for "bundle.js".

The `IFileProvider` interface at the moment only allows watching a single include pattern.

This would be more useful:

```
IChangeToken Watch(string[] includePatterns, string[] excludePatterns);
```

**Comment by dazinator** [comment]
include and exclude are also useful when searching for files, however this was easier to solve, as you can write your own searching implementation like I have done here - which walks the directory from the provider and evaulates whether the file matches any of the include patterns, and if it does, also verifies it doesn't match any of the exclude patterns:

https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders/blob/fde58f8649ea4deb6721814aa65d61f414ec8ed1/src/Dazinator.AspNet.Extensions.FileProviders/GlobMatchingEnumerableFileInfos.cs#L11

However watching() is different, because the underlying provider can only watch a single pattern and has no concept of exclude. So to implement an extension method that would do a watch() using an include and exclude list, you'd currently have to have the underlying provider watch more files than necessary for changes, and then evaluate against the exclude filters after change tokens have been signalled. This is possible but not the best from a performance perspective as change tokens are still signalled when not necessary.

**Comment by dazinator** [comment]
Any thoughts on this anyone?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2544
