### ISSUE TITLE
EmbeddedFileProvider not working correctly with MSBuild when default Namespace != Assembly name

### ISSUE THREAD

**Issue by tidyui** [aspnet/FileSystem#262]
I've converted a project.json to msbuild and all embedded resources stopped working. My guess is that the problem lies in this line here:

https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Embedded/EmbeddedFileProvider.cs#L34

I'm assuming that ResourceManifestNames for project.json build was always generated from Assembly name, however when I switched to msbuild they were again generated from Default namespace. In my case they are not identical so no files are found, however when I call GetResourceManifestInfo directly I get back the info for the file.

Regards

**Comment by natemcmaster** [comment]
This is likely not an issue with the embedded file provider, as the provider is agnostic to whether the assembly was compiled via project.json or MSBuild.

In MSBuild, you can control the resources' manifest names by adding the `<RootNamespace>` property to your \*.csproj file. This value [defaults to the filename](https://github.com/dotnet/sdk/blob/dev15.0.x/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L40-L41) of your \*.csproj. Can you try setting this instead?

Alternatively, you can use the `public EmbeddedFileProvider(Assembly assembly, string baseNamespace)` overload where `baseNamespace` is set to your project's root namespace.

**Comment by tidyui** [comment]
Yes this was exactly what I wrote :) When the project was compiled without MSBuild the resources manifest names were **always** based on Assembly name as opposed to MSBuild where it is based on root namespace. To me having a constructor without `baseNamespace` is **wrong** as functionality of the provider can not be guaranteed. The provider then bluntly **assumes** that the root namespace is the same as the assembly name which is just not a safe assumption.

Regards

**Comment by pranavkm** [comment]
> To me having a constructor without baseNamespace is wrong as functionality of the provider can not be guaranteed. 

Perhaps we can call this out in the `summary` of the ctor. In the default case, this just works, so it seems like a loss of convenience to remove it.

**Comment by muratg** [comment]
Agreed with @pranavkm. We can have better docs to guide folks towards using [this overload](https://github.com/aspnet/FileSystem/blob/72d77a0b665e6a9d9ef7f36033551ccfa56892d2/src/Microsoft.Extensions.FileProviders.Embedded/EmbeddedFileProvider.cs#L44)
