### ISSUE TITLE
Test: TokensFiredForNewDirectoryContentsOnRename sometimes fails on Windows 10

### ISSUE THREAD

**Issue by jbagga** [aspnet/FileSystem#263]
[TokensFiredForNewDirectoryContentsOnRename](https://github.com/aspnet/FileSystem/blob/dev/test/Microsoft.Extensions.FileProviders.Physical.Tests/PhysicalFileProviderTests.cs#L1138) failed on the CI a few times in the past week.

cc @muratg

**Comment by ryanbrandenburg** [comment]
This is [still happening](http://aspnetci/viewLog.html?buildId=441190&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId-7947063349423447523). Future instances of it can be seen [here](http://aspnetci/project.html?tab=testDetails&testNameId=-7947063349423447523&projectId=XPlat&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by Eilon** [comment]
This issue was moved to aspnet/Home#3033
