### ISSUE TITLE
EmbeddedFileProvider should not be compiled for netstandard1.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/FileSystem#267]
The comment here says we should remove the TFM in 2.0: https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Embedded/EmbeddedFileProvider.cs#L57

**Comment by pranavkm** [comment]
cc @muratg - we should try and sort this for 2.0 if we plan on doing this.

**Comment by natemcmaster** [comment]
I tracked down the history of this comment. It was added here: https://github.com/aspnet/FileSystem/pull/210 cc @BrennanConroy 

@muratg any reason we should keep netstandard1.0?

**Comment by muratg** [comment]
@natemcmaster So it'll be netstandard1.5 only? I think it should be fine -- any objections @davidfowl?

**Comment by natemcmaster** [comment]
Dropping netstandard1.0 means dropping:

- Universal Windows Platform 10
- Windows Phone 8.0, 8.1	
- Windows Phone Silverlight

**Comment by pranavkm** [comment]
Fixed as part of targeting netstandard2.0 (https://github.com/aspnet/FileSystem/commit/c0e09fdbe1950d7047f39d373abfebcc1fd4553d).
