### ISSUE TITLE
Add baselines to enable checks for breaking changes

### ISSUE THREAD

**Issue by dougbu** [aspnet/FileSystem#268]
One shipped project in this repo lacks baselines. Looks like baseline files (`baseline.net45.json` and `baseline.netcore.json`) should be created in `release` or `rel/1.0.1` and checked into at least `dev`. The details below are reformatted from a recent Universe build on the CI.
```
[FileSystem\src\Microsoft.Extensions.FileProviders.Embedded\Microsoft.Extensions.FileProviders.Embedded.csproj]
  No baseline file for net46 found in Microsoft.Extensions.FileProviders.Embedded.
```

**Comment by natemcmaster** [comment]
This isn't necessary anymore now that we only target .NET Standard 2.0 (see #276 ). We already had baseline.netcore.json file.
