### ISSUE TITLE
Make WriteContent of IFileInfo interface take in a Stream

### ISSUE THREAD

**Issue by Praburaj** [aspnet/FileSystem#29]
Currently it takes in a `byte[]`. Its not helpful if one want to write large amounts of data. This will also make it symmetric to the `CreateReadStream()` API.

**Comment by hishamco** [comment]
@Praburaj Regarding the issue #41 this issue should be mark as "Closed"

**Comment by Praburaj** [comment]
@hishamco thanks 😊.
