### ISSUE TITLE
Provide a zipped file provider

### ISSUE THREAD

**Issue by Tratcher** [aspnet/FileSystem#292]
Consider a file provider that exposes the contents of a zip file. There may also be optional caching of the unzipped content of individual files. This could be used to reduce project publish size, time, etc..

**Comment by natemcmaster** [comment]
Duplicate of https://github.com/aspnet/FileSystem/issues/213. We discussed before and decided not to implement this. Any reason to reconsider?

**Comment by Tratcher** [comment]
@DamianEdwards and I were discussing different ways to reduce app deployment size, and the static wwwroot assets are the one of the largest pieces. I put together a sample here:
https://github.com/Tratcher/ZipFileProviderExp/blob/729bff83b63022e7a666bb6c33e424a4e0afe9f7/SampleSite/Program.cs#L26
It reduced the template static assets size from 2.4mb to 600kb.

The actual solution he wants is to pre-gzip the individual files and serve them directly to the client with the proper compression headers, but all of that logic needs to be built into the StaticFiles middleware.

**Comment by muratg** [comment]
Tentatively putting this in 2.2.0.  I suspect we'll possibly punt it again after talking about some details.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2541
