### ISSUE TITLE
Use FileProvider to stream views and static files hosted in the cloud

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/FileSystem#295]
Is it possible to use any `IFileProvider` implementation, or any other feature to load views and static files via `http`?

What I'm trying to achieve is to have an interface in my MVC app that is accessible via `http://domain.com/myarea` that loads the `_Layout.cshtml`, all views and static files for that specific area without having them on disk?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2539
