### ISSUE TITLE
Support GetFileInfo for directories

### ISSUE THREAD

**Issue by stilettk** [aspnet/FileSystem#298]
Currently `GetFileInfo` supports only files: when called on a path that points to a directory it returns `PhysicalFileInfo` which has `IsDirectory == false`. 

So, when given a path, how to decide what to do: to call `GetFileInfo` (if it's a file) or call `GetDirectoryContents` (if it's a folder)? Currently the only way I found isn't very intuitive:
`bool isDirectory = fileProvider.GetDirectoryContents(myPath).Exists`

My suggestion:
`new PhysicalFileProvider(myPath).GetFileInfo("data")` 
Expected:
`PhysicalDirectoryInfo`
Actual:
`PhysicalFileInfo`

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2537
