### ISSUE TITLE
Update doc comments for EmbeddedFileProvider constructor without namespace argument

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/FileSystem#300]
The EmbeddedFileProvider constructor defaultNamespace is NOT correct when the Assembly Default Namespace is not the same as the name of the assembly

```
> public EmbeddedFileProvider(Assembly assembly)
>             : this(assembly, assembly?.GetName()?.Name)
>         {
>         }
```

**Comment by pranavkm** [comment]
@grahamehorner is there a better way to get to the configured default namespace? The code here is a best effort guess that follows the SDK's convention of using the assembly name as the default namespace.

**Comment by grahamehorner** [comment]
@pakrym I've wrote and extension method to IList<IFileProvider> which accepts a type and resolves both the assembly & namespace and add the EmeddedFileProvider to the IList<IFileProvider> as a solution for me; I think the constructor comment needs updated to be informative of this limitation/assumption

**Comment by pranavkm** [comment]
> I think the constructor comment needs updated to be informative of this limitation/assumption

We'd be happy to accept a PR for this.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/FileSystem/commit/bd96038a174eb960b2fdd3f160636aa09b1f98af
