### ISSUE TITLE
PhysicalDirectoryInfo.PhysicalPath should return relative path

### ISSUE THREAD

**Issue by jiatao99** [aspnet/FileSystem#306]
Call provider.GetDirectoryContents("") might return a PhysicalDirectoryInfo. From there, I should be able to call the provider.GetDirectoryContents(dir.PhysicalPath) to retrieve the directory content from sub folder. However, the PhysicalDirectoryInfo.PhysicalPath returns the absolute path.

Since PhysicalFileProvider only take relative path, I have no easy way to recursively list all the directory contents in the file system. 

In my opinion, both PhysicalDirectoryInfo and PhysicalFileInfo should always return relative path (to provider) to follow the design pattern

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2533
