### ISSUE TITLE
CompositeFileProvider should implement IDisposable

### ISSUE THREAD

**Issue by jiatao99** [aspnet/FileSystem#307]
1. I implement my own IFileProvider (like Zip)  and implement IDisposable
2. I add my provider into CompositeFileProvider
3. I add CompositeFileProvider into ServiceCollection 

Result:  my provider will not be disposed properly

CompositeFileProvider should implement IDisposable and dispose inner providers.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2532
