### ISSUE TITLE
Remove RestrictedFileNames checks

### ISSUE THREAD

**Issue by glennc** [aspnet/FileSystem#37]
A unit test should be created to test that nothing causes problems. The IO layer will protect us from what it is trying to achieve.

// @blowdart

**Comment by Praburaj** [comment]
@glennc @blowdart what do we want to verify in the unit test?

**Comment by blowdart** [comment]
Hmm, nothing really. Not sure what we can test here.

**Comment by Praburaj** [comment]
sounds good. Let me send a PR.

**Comment by Praburaj** [comment]
https://github.com/aspnet/FileSystem/commit/ee72e744ffa8294b7e7caa9a99052da363e5ddea
