### ISSUE TITLE
Make sure that EnsureTrailingSlash works on non-windows platforms

### ISSUE THREAD

**Issue by glennc** [aspnet/FileSystem#38]
EnsureTrailingSlash needs to add the correct slash to the end of the path for the OS.

**Comment by muratg** [comment]
https://github.com/aspnet/FileSystem/blob/325d550fa9e04be9927547123c5dd7c55d8e127a/src/Microsoft.AspNet.FileProviders.Physical/PhysicalFileProvider.cs#L75
