### ISSUE TITLE
GetFullPath should use concatenation

### ISSUE THREAD

**Issue by glennc** [aspnet/FileSystem#39]
GetFullPath can concatenate instead of doing Path.Combine. This saves us from situations where Path.Combine will ignore part of the provided path if it is rooted.

Method should fail if someone is asking for a rooted file. Once this is done then GetFileInfo can also have unnecessary guard clauses removed. 

// @blowdart

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2565
