### ISSUE TITLE
Rename IFileSystem to something more web specific

### ISSUE THREAD

**Issue by davidfowl** [aspnet/FileSystem#4]
Sounds too general at the moment and it's really only about reading files from under the application root.

**Comment by Tratcher** [comment]
*Provider
Ms.Aspnet.FileProviders
IFileProvider
PhysicalFileProvider
EmbeddedFileProvider

**Comment by Tratcher** [comment]
@davidfowl @Eilon do you also want to rename the repo?

**Comment by Eilon** [comment]
Renaming the repo :frowning: Maybe eventually. GitHub does automatically do redirects for such renames but I'm not sure if it redirects for scenarios like cloning, etc. I'm fine waiting for some future time where we'd rename this along with other stuff...

**Comment by Tratcher** [comment]
@Eilon  Github is now gracefully redirecting for repo renames. See http://github.com/aspnet/kvm

**Comment by Eilon** [comment]
Yeah I just saw that earlier... I'm fine with renaming it. Just let me know when (because we have to update Universe, CIs, etc.).

**Comment by Tratcher** [comment]
Whenever you're ready. It won't impact my MVC fixes.

**Comment by Eilon** [comment]
Done.
