### ISSUE TITLE
Consider EmbeddedFileSystem becoming its own NuGet package

### ISSUE THREAD

**Issue by glennc** [aspnet/FileSystem#48]

**Comment by Praburaj** [comment]
Microsoft.AspNet.FileProviders (common stuff between providers - this contains implementation of `NoopTrigger`, `EnumerableDirectoryContents`, `NotFoundDirectoryContents` and `NotFoundFileInfo` etc..)
Microsoft.AspNet.FileProviders.Physical
Microsoft.AspNet.FileProviders.Embedded
Microsoft.AspNet.FileProviders.Interfaces
