### ISSUE TITLE
Update Matcher and its abstractions to remove the bits not actually needed

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/FileSystem#57]
Parts of `Matcher` and its abstractions (e.g. `DirectoryInfoBase`) were written to support more functionality that it turns out we don't need, e.g. listing files in a directory with a pattern. We should remove the unneeded bits as they're incompatible with `IFileProvider` and not needed anyway.

**Comment by DamianEdwards** [comment]
There's an implementation using `IFileProvider` of the abstractions `Matcher` uses at https://github.com/aspnet/Mvc/blob/LinkTagHelperGlobbing-1581/src/Microsoft.AspNet.Mvc.TagHelpers/Internal/FileProviderGlobbingDirectory.cs

**Comment by troydai** [comment]
https://github.com/aspnet/FileSystem/commit/3a00f0b05b163120a66ea6a1ec048aee34451dbd
