### ISSUE TITLE
FileSystemGlobbing documentation

### ISSUE THREAD

**Issue by Mpdreamz** [aspnet/FileSystem#62]
This looks pretty rad:

https://github.com/aspnet/FileSystem/tree/dev/src/Microsoft.Framework.FileSystemGlobbing

But lacks documentation (a simple readme.md would suffice). 

Feature wise it should be on par with https://github.com/isaacs/minimatch/ which is what most npm modules use for globbing. 

Many of the supported globbing options in @editorconfig for instance follow the same feature set of minimatch.

**Comment by am11** [comment]
There is an implementation of `minimatch` in C# by @SLaks: https://github.com/slaks/minimatch. It is well tested, and all the `minimatch` rules in their documentation applies. 

Perhaps AspNet team can make use it?

**Comment by davidfowl** [comment]
Not likely, this library was written for a few reasons.

- Regex is slow, we don't want it
- We're very performance sensitive includes and excludes need to be evaluated folder by folder (so we don't enumerate the exclude to figure out what to exclude).

**Comment by muratg** [comment]
@Mpdreamz There's some documentation and examples of usage [here](http://docs.asp.net/en/latest/dnx/projects.html).
