### ISSUE TITLE
Support optional sets in globbing patterns, e.g. {js,min.js}

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/FileSystem#67]
Add support to the `Matcher` for globbing patterns containing `{}` comma-separated lists of "OR" patterns. This would be really useful in the Tag Helper case for including files with similar, but different, extensions, or segments.

See http://gruntjs.com/configuring-tasks#globbing-patterns

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2562
