### ISSUE TITLE
Custom Exclusion - bower_components and Node_modules are excluded - how to exclude more?

### ISSUE THREAD

**Issue by xtianus79** [aspnet/FileSystem#74]
1) How is bower_components excluded exactly? I tried renaming it in project.json but didn't change the behavior
2) How to exclude myfolder in src/project_name/
3) Why don't we have Exclude option when we right click in solution explorer

**Comment by davidfowl** [comment]
This is in the wrong place. Can you file this bug on the Home repository.

**Comment by xtianus79** [comment]
filesystem seems like a logical choose no?

**Comment by am11** [comment]
@davidfowl, there are also other exclude related issues opened in this repo, which were redirected from Home repo. For instance #71.
